@baseUrl = http://localhost:3000

### Read all compagnies 
GET {{baseUrl}}/compagnies

### Read company with id 1
GET {{baseUrl}}/compagnies/16

### Register Company
POST {{baseUrl}}/compagnies/register
Content-Type: application/json

{
    "company_name": "testcomp",
    "description": "DESCRIPTION ..........",
    "adress" : "rue ........",
    "mail" : "testcomp9@gmail.com",
    "password": "123"    
}



### Read company with id 2
GET {{baseUrl}}/compagnies/matchesCompany/1

