@baseUrl = http://localhost:3000

### Read all compagnies 
GET {{baseUrl}}/compagnies

### Read company with id 1
GET {{baseUrl}}/compagnies/4

### Register Company
POST {{baseUrl}}/compagnies/register
Content-Type: application/json

{
    "company_name": "Carrefour",
    "description": "DESCRIPTION ..........",
    "adress" : "rue ........",
    "mail" : "gb@gmail.com",
    "password": "$2b$10$5eojzYN447x3npFQvLwTG.m5P/3ThamImtCOGs849tPMQrDZuSa5C"    
}





