@baseUrl = http://localhost:3000

### Read all developers
GET {{baseUrl}}/developers

### Read developers by his mail return his password 
GET {{baseUrl}}/developers/login/f.m@gmail.com


### login test 
POST {{baseUrl}}/developers/login
Content-Type: application/json

{
    "mail":"f.m@gmail.com",
    "password":"123"
}


### Read developers register
POST {{baseUrl}}/developers/registerDev
Content-Type: application/json

{
    "lastname":"M",
    "firstname": "M",
    "mail":"MM@student.be",
    "password":"pass123",
    "birth_date": "2000-01-02",
    "tel":"0487789001",
    "type_offer_required": "1" 
}

###

POST {{baseUrl}}/developers/login
Content-Type: application/json

{
    "email":"brahim.abid@student.vinci.be",
    "password":"password"
 
}

### Read devlopper profile by id
GET {{baseUrl}}/developers/profileDev/5

### Read devlopper master languages by id
GET {{baseUrl}}/developers/masteredLanguageDev/5

### Read devlopper master languages by id
GET {{baseUrl}}/developers/getAllLanguages

### Read devlopper master languages by id

POST  {{baseUrl}}/developers/addLanguageProgramation
Content-Type: application/json

{
    "idDev":"5",
    "idLanguage":"3"
 
}
