@baseUrl = http://localhost:3000

### Read all developers
GET {{baseUrl}}/developers

### Read developers by his mail return his password 
GET {{baseUrl}}/developers/login/brahim.abid@student.vinci.be


### Read developers register
POST {{baseUrl}}/developers/registerDev
Content-Type: application/json

{
    "lastname":"M",
    "firstname": "M",
    "mail":"MM@student.be",
    "password":"pass123",
    "birth_date": "2000-01-02",
    "tel":"0487789001",
    "type_offer_required": "1" 
}