@baseUrl = http://localhost:3000

### Read all developers
GET {{baseUrl}}/developers

### Read developers by his mail return his password 
GET {{baseUrl}}/developers/login/brahim.abid@student.vinci.be


### login test 
GET {{baseUrl}}/developers/login
Content-Type: application/json

{
    "mail":"brahim.abid@student.vinci.be",
    "password":"password"
}


### Read developers register
GET {{baseUrl}}/developers/registerDev
Content-Type: application/json

{
    "lastname":"A",
    "firstname": "o",
    "mail":"email@test.be",
    "password":"password",
    "birth_date": "2000-01-02",
    "tel":"0487878787",
    "type_offer_required": "1" 
}