@baseUrl = http://localhost:3000

### Read all job offers
GET {{baseUrl}}/jobOffers

### CREATE INTERSTED FOR DEV
POST {{baseUrl}}/jobOffers/addToInterstedDev
Content-Type: application/json

{
    "idOffer":"1",
    "idDeveloper":"4"
}

### DELETE INTERESTED FOR DEV
POST {{baseUrl}}/jobOffers/notInterestedDev
Content-Type: application/json

{
    "idOffer":"1",
    "idDeveloper":"4"
}

### Read all job offers from company
GET {{baseUrl}}/jobOffers/allJobOfferFromCompany/25


### Read All developers intersted of one jobOffer
GET {{baseUrl}}/jobOffers/allDevelopersInterstedOffer/55


### CREATE job offer
POST {{baseUrl}}/jobOffers/create/25
Content-Type: application/json

{
    "typeOffer": "2",
    "title": "recherche developpeur full-stack ",
    "description": "DESCRIPTION .........."
}


### Read All type offer
GET {{baseUrl}}/jobOffers/allTypeOffer



### Read all infos of dev that have a complete match with company by id offer
GET {{baseUrl}}/jobOffers/getMatchesDevAndCompnay/50

### Read All infos of companies that have complete match by id developeur
GET {{baseUrl}}/jobOffers/getCompaniesMatchInfos/5

### Read All infos of job offer by id company by id developeur for complete macth
GET {{baseUrl}}/jobOffers/getJobOffersMatchInfos/25/1



### Read company with id 2
GET {{baseUrl}}/jobOffers/likedOffers/25

### Read company with id 2
POST {{baseUrl}}/jobOffers/dislikeDev/3/55

### Like developer for an offer 
POST {{baseUrl}}/jobOffers/likeDev/4/5

### Read language_required of offer
GET {{baseUrl}}/jobOffers/getLanguageRequired/2

### Read All language
GET {{baseUrl}}/jobOffers/getAllLanguages

### Add a language to an offer
GET {{baseUrl}}/jobOffers/addLanguageToOffer
Content-Type: application/json

{
    "offer": "2",
    "language": "6"
}



