@baseUrl = http://localhost:3000

### Read all job offers
GET {{baseUrl}}/jobOffers

### CREATE INTERSTED FOR DEV
POST {{baseUrl}}/jobOffers/addToInterstedDev
Content-Type: application/json

{
    "idOffer":"60",
    "idDeveloper":"1"
}

### Read all job offers from company
GET {{baseUrl}}/jobOffers/allJobOfferFromCompany/25


### Read All developers intersted of one jobOffer
GET {{baseUrl}}/jobOffers/allDevelopersInterstedOffer/55


### CREATE job offer
POST {{baseUrl}}/jobOffers/create/25
Content-Type: application/json

{
    "typeOffer": "2",
    "title": "recherche developpeur full-stack ",
    "description": "DESCRIPTION .........."
}


### Read All type offer
GET {{baseUrl}}/jobOffers/allTypeOffer

### Read company with id 2
GET {{baseUrl}}/jobOffers/likedOffers/25

### Read company with id 2
POST {{baseUrl}}/jobOffers/dislikeDev/3/55